# Generated by Django 3.0.3 on 2021-02-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeaData', '0004_auto_20210216_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='recieve_report',
            field=models.BooleanField(default=False),
        ),
    ]
